"""Persistence contracts the services depend on (dependency inversion).

Services receive objects satisfying these protocols, so they can be tested
against any storage and never import SQLAlchemy sessions.
"""
from typing import List, Optional, Protocol, Tuple

from ..models import DNSRecord, HostedZone, User


class UserRepository(Protocol):
    def get_by_username(self, username: str) -> Optional[User]: ...
    def add(self, user: User) -> User: ...
    def save(self, user: User) -> User: ...


class ZoneRepository(Protocol):
    def get(self, zone_id: str) -> Optional[HostedZone]: ...
    def search(
        self, query: Optional[str], sort_by: str, descending: bool, offset: int, limit: int
    ) -> Tuple[List[HostedZone], int]: ...
    def add(self, zone: HostedZone, records: List[DNSRecord]) -> HostedZone: ...
    def save(self, zone: HostedZone) -> HostedZone: ...
    def delete(self, zone: HostedZone) -> None: ...
    def count(self) -> int: ...
    def delete_all(self) -> int: ...


class RecordRepository(Protocol):
    def get(self, zone_id: str, record_id: str) -> Optional[DNSRecord]: ...
    def search(
        self,
        zone_id: str,
        query: Optional[str],
        record_type: Optional[str],
        sort_by: Optional[str],
        descending: bool,
        offset: int,
        limit: int,
    ) -> Tuple[List[DNSRecord], int]: ...
    def list_all(self, zone_id: str) -> List[DNSRecord]: ...
    def find_by_name(self, zone_id: str, name: str) -> List[DNSRecord]: ...
    def add(self, record: DNSRecord) -> DNSRecord: ...
    def save(self, record: DNSRecord) -> DNSRecord: ...
    def delete_many(self, zone_id: str, records: List[DNSRecord]) -> None: ...
