from typing import List

import dns.rdatatype
import dns.zone

from ..models import DNSRecord, HostedZone
from .base import ZoneFormat

_TYPE_ORDER = {"SOA": 0, "NS": 1}


def _relative_name(record_name: str, zone_name: str) -> str:
    if record_name == zone_name:
        return "@"
    suffix = "." + zone_name
    return record_name[: -len(suffix)] if record_name.endswith(suffix) else record_name


class BindFormat(ZoneFormat):
    name = "bind"
    extension = "zone"
    media_type = "text/plain"

    def dump(self, zone: HostedZone, records: List[DNSRecord]) -> str:
        lines = [f";; BIND zone file for {zone.name}", ";; Generated by Route 53 Clone", f"$ORIGIN {zone.name}", ""]
        ordered = sorted(records, key=lambda r: (_TYPE_ORDER.get(r.type, 2), r.name, r.type))

        for record in ordered:
            name = _relative_name(record.name, zone.name)
            if record.alias:
                # BIND has no alias concept; keep the information as a comment.
                lines.append(f"; ALIAS {name} {record.type} -> {record.alias_target}")
                continue
            if record.routing_policy == "Weighted":
                lines.append(f"; weighted record set_id={record.set_id} weight={record.weight}")
            for value in filter(None, (v.strip() for v in record.value.split("\n"))):
                if record.type == "TXT" and not (value.startswith('"') and value.endswith('"')):
                    value = f'"{value}"'
                lines.append(f"{name}\t{record.ttl}\tIN\t{record.type}\t{value}")
        return "\n".join(lines) + "\n"

    def parse(self, text: str, zone_name: str) -> List[dict]:
        try:
            zone = dns.zone.from_text(text, origin=zone_name, relativize=False, check_origin=False)
        except Exception as exc:  # dnspython raises many specific exception types
            raise ValueError(f"Failed to parse BIND zone file: {exc}") from exc

        parsed = []
        for node_name, node in zone.nodes.items():
            for rdataset in node.rdatasets:
                values = [rdata.to_text() for rdata in rdataset]
                if values:
                    parsed.append(
                        {
                            "name": str(node_name),
                            "type": dns.rdatatype.to_text(rdataset.rdtype),
                            "ttl": rdataset.ttl,
                            "value": "\n".join(values),
                        }
                    )
        return parsed
